### PR TITLE
fix(cli): run storybook in `development` env

### LINKED ISSUE #38: Reload TailwindCSS classes
I've just set up a project with TailwindCSS. While working on a component I noticed that classes do not reload on change. For example, if I wanted to modify a padding `p-2` to `p-4`, I have to completely reload Storybook. I've noticed this behavior in the example too.

Is there anything I can do to make them reload on save?

### PR DESCRIPTION
**Pull request by farnabaz**
Make sure NODE_ENV is `development`.
**NOTE:** While using `nuxt` to execute commands, Nuxt set NODE_END to `production` if it is missing.

see: https://github.com/nuxt/nuxt.js/blob/dev/packages/cli/src/setup.js#L9

Fix #38

## Types of changes

- [X] Bug fix (a non-breaking change which fixes an issue)
- [ ] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes (if not applicable, please state why)

### CODE REVIEW

**Comment by farnabaz** [comment]
@pi0 Do you think we can do better than this?

File: src/cli.ts [hunk 1]
```diff
@@ -28,6 +28,10 @@ function _run () {
         mode
       })
     case 'dev':
+      // Make sure NODE_ENV is `development`.
+      // NOTE: While using `nuxt` to execute commands, Nuxt set NODE_END to `production` if it is missing.
```
Comment (pi0) [inline src/cli.ts:32]:
```suggestion
      // NOTE: While using `nuxt` to execute commands, Nuxt set NODE_ENV to `production` if it is missing.
```

**Comment by pi0** [comment]
@farnabaz Unfortunately not.
